baseurl: ''
exclude: ['README.md']
permalink: pretty
title: '半兆科技'

collections:
  services:
    output: true
    permalink: /services/:path/
  # team:
  #   output: true
  #   permalink: /team/:path/
  # testimonials:
  #   output: true
  #   permalink: /testimonials/:path/
  policy:
    output: true
    permalink: /policy/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true
  - scope:
      type: policy
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: null

plugins:
  - jekyll-environment-variables
